package com.mercari.roadtripgames.numberplate

enum class NumberPlateType(
    val slogan: String
) {
    ALABAMA("God Bless America"),
    ALASKA("The Last Frontier"),
    ARIZONA("Grand Canyon State"),
    ARKANSAS(""),
    CALIFORNIA(""),
    COLORADO(""),
    CONNECTICUT("Constitution State"),
    DELAWARE("The First State"),
    DISTRICT_OF_COLUMBIA("Taxation Without Representation"),
    FLORIDA(""),
    GEORGIA(""),
    HAWAII("Aloha State"),
    IDAHO("Famous Potatoes"),
    ILLINOIS("Land of Lincoln"),
    INDIANA("The Crossroads of America"),
    IOWA("Ad Astra per Aspera"),
    KANSAS(""),
    KENTUCKY(""),
    LOUISIANA("Sportsman's Paradise"),
    MAINE("Support Wildlife"),
    MARYLAND(""),
    MASSACHUSETTS("The Spirit of America"),
    MICHIGAN(""),
    MINNESOTA("10,000 Lakes"),
    MISSISSIPPI(""),
    MISSOURI("Show Me State"),
    MONTANA("Treasure State"),
    NEBRASKA(""),
    NEVADA(""),
    NEW_HAMPSHIRE("Live Free or Die"),
    NEW_JERSEY("Garden State"),
    NEW_MEXICO("Land of Enchantment"),
    NEW_YORK("Empire State"),
    NORTH_CAROLINA("First in Freedom"),
    NORTH_DAKOTA("Peace Garden State"),
    OHIO(""),
    OKLAHOMA(""),
    OREGON(""),
    PENNSYLVANIA("Keystone State"),
    RHODE_ISLAND("Ocean State"),
    SOUTH_CAROLINA(""),
    SOUTH_DAKOTA("Great Faces, Great Places"),
    TENNESSEE(""),
    TEXAS("The Lone Star State"),
    UTAH(""),
    VERMONT("Green Mountain State"),
    VIRGINIA("Virginia is for Lovers"),
    WASHINGTON("Evergreen State"),
    WEST_VIRGINIA("Wild, Wonderful"),
    WISCONSIN("America's Dairyland"),
    WYOMING("")
}
